name: Update exchange rates

on:
  schedule:
    - cron: "0 20 * * *"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: mvn install

      - name: Run the project
        env:
          API_TOKEN_BMX: ${{ secrets.API_TOKEN_BMX }}
        run: mvn exec:java

      - name: Commit changes
        run: |
          git config --global user.email "dev@asjordi.dev"
          git config --global user.name "Jordi Ayala"
          git add data.json lastUpdate.txt
          git diff --staged --quiet || git commit -m 'chore: Update data'
          git push
